# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: example.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import example_pb2


class ExampleServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SayHello(self, stream: 'grpclib.server.Stream[example_pb2.HelloRequest, example_pb2.HelloResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/example.ExampleService/SayHello': grpclib.const.Handler(
                self.SayHello,
                grpclib.const.Cardinality.UNARY_UNARY,
                example_pb2.HelloRequest,
                example_pb2.HelloResponse,
            ),
        }


class ExampleServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SayHello = grpclib.client.UnaryUnaryMethod(
            channel,
            '/example.ExampleService/SayHello',
            example_pb2.HelloRequest,
            example_pb2.HelloResponse,
        )
